chat/urls.py
from django.urls import path, re_path


from .views import ThreadView, InboxView

app_name = 'chat'
urlpatterns = [
    path("", InboxView.as_view(), name="room-list"),
    re_path(r"^(?P<pk>\d+)", ThreadView.as_view(), name='room'),
]

financialchat/urls.py
# from django.contrib import admin
# from django.urls import path

# from django.contrib.auth.views import LoginView
# from profiles.views import RegisterView

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('login/', LoginView.as_view(), name="login"),
#     path('register/', RegisterView.as_view(), name="register")
# ]

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rooms/', include('chat.urls', namespace='chat')),
    path('', include('profiles.urls', namespace='profiles')),
]

profiles/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView
from profiles.views import RegisterView

app_name = 'profiles'
urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('register/', RegisterView.as_view(), name="register")
]

chat/models.py
from django.db import models
from django.conf import settings


class Thread(models.Model):

    name = models.CharField('Room name', max_length=70,
                            null=False, blank=False)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)


class ChatMessage(models.Model):
    thread = models.ForeignKey(
        Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             verbose_name='sender', on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

core/models.py
from django.db import models


class TimestampedModel(models.Model):

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:

        abstract = True
        ordering = ['-updated_at', '-created_at']

profiles/models.py
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager, PermissionsMixin
)
from django.db import models
from core.models import TimestampedModel


class UserManager(BaseUserManager):

    def create_user(self, username, email, password=None):

        if username is None:
            raise TypeError('Users must have a username.')

        if email is None:
            raise TypeError('Users must have an email adress')
        user = self.model(username=username, email=self.normalize_email(email))
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, email, password):

        if password is None:
            raise TypeError('Superusers must have a password')
        user = self.create_user(username, email, password)
        user.is_superuser = True
        user.is_staff = True
        user.save()

        return user


class User(AbstractBaseUser, PermissionsMixin, TimestampedModel):

    username = models.CharField(db_index=True, max_length=255, unique=True)
    email = models.EmailField(db_index=True, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = UserManager()

    def __str__(self):

        return self.email

    def get_full_name(self):

        return self.username

    def get_short_name(self):

        return self.username

chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control"}
        )
    )


class RoomForm(forms.Form):

    name = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control"}
        )
    )

profiles/forms.py
from django import forms

from .models import User


class RegisterForm(forms.ModelForm):

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email',)

    def clean_email(self):
        email = self.cleaned_data.get("email")
        qs = User.objects.filter(email__iexact=email)
        if qs.exists():
            raise forms.ValidationError(
                "Cannot use this email. It's already registered")
        return email

    def clean_password2(self):

        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):

        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active = True
        if commit:
            user.save()
        return user

chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.views.generic.edit import FormMixin
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView

from .forms import ComposeForm, RoomForm
from .models import Thread


class InboxView(LoginRequiredMixin, FormMixin, ListView):
    template_name = 'chat/inbox.html'
    form_class = RoomForm
    success_url = '/rooms'

    def get_queryset(self):
        return Thread.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        name = form.cleaned_data.get("name")
        Thread.objects.create(name=name)
        return super().form_valid(form)


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = './'

    def get_object(self):
        id_ = self.kwargs.get("pk")
        obj = get_object_or_404(Thread, pk=id_)

        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()

        thread = self.get_object()

        context['chat_messages'] = thread.chatmessage_set.all().order_by(
            '-timestamp')[:50]
        return context

profiles/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import RegisterForm


class RegisterView(CreateView):

    form_class = RegisterForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('profiles:login')

    def dispatch(self, *args, **kwargs):

        return super(RegisterView, self).dispatch(*args, **kwargs)

chat/templates/chat/inbox.html
{% extends "base.html" %}

{% block content %}

<form id='form' method='POST'> {% csrf_token %}
{{form.as_p }}
<input type='submit' value='Create room' class='btn btn-primary'/>
</form>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th>ID</th>
      <th>Room name</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
  	{% for room in object_list %}

    <tr>
      <th scope="row">{{room.id}}</th>
      <td>{{room.name}}</td>
      <td><a href="{% url 'chat:room' room.id %}"  class="btn btn-primary">Enter room</a></td>
    </tr>

  	{% endfor %}
  </tbody>
</table>



{% endblock %}

chat/templates/chat/thread.html
{% extends "base.html" %}

{% block content %}
<h3>Room: {{ object.name }}</h3>
<ul id='chat-items'>
{% for chat in chat_messages reversed %}

<li>{{ chat.message }} via {{ chat.user.username }}</li>

{% endfor %}
</ul>

<form id='form' method='POST'> {% csrf_token %}
	<input type="hidden" id='myUsername' value='{{ user.username }}' />
{{form.as_p }}
<input type='submit' value="Send" class='btn btn-primary'/>
</form>

{% endblock %}

{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.js"></script>

<script>

let loc = window.location
let formData = $('#form')
let msgInput = $('#id_message')
let chatHolder = $('#chat-items')
let me = $("#myUsername").val()
let wsStart = 'ws://'
if (loc.protocol == 'https:'){
	wsStart = 'wss://'
}
let endpoint = wsStart + loc.host + loc.pathname
let socket = new ReconnectingWebSocket(endpoint)

socket.onmessage = function(e){

	console.log("message", e)
	let chatDataMsg = JSON.parse(e.data)
	chatHolder.append('<li>'+ chatDataMsg.message + ' vía ' + chatDataMsg.username +'</li>')

}

socket.onopen = function(e){
	console.log("open", e)
	formData.submit(function(event){
		event.preventDefault()
		let msgText = msgInput.val()
		let finalData = {
			'message': msgText
		}
		socket.send(JSON.stringify(finalData))
		formData[0].reset()
	})
}

socket.onerror = function(e){
	console.log("error", e)
}

socket.onclose = function(e){
	console.log("close", e)
}
</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang=en>
	<head>
		<title>{% block head_title %}FinancialChat.com{% endblock head_title %}</title>
		{% include 'css.html' %}
	</head>
	<body>
		<div class="container">
			<h1>FinancialChat</h1>
		</div>
		<div class='container'>
			{% block content %}{% endblock content %}
		</div>
		{% include 'js.html' %}
		{% block script %}
		{% endblock %}
	</body>
</html>

templates/css.html
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">

templates/home.html
{% extends "base.html" %}

{% block content %}

<p class='lead'>Welcome Home</p>
{% endblock %}

templates/js.html
 <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script
  src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>